// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocketServer.Data;

#nullable disable

namespace SocketServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240928223456_InitialTables")]
    partial class InitialTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SocketServer.Entities.Device", b =>
                {
                    b.Property<int>("IdDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AlterationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("AvailableSpace")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OccupiedSpace")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserIdUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDevice");

                    b.HasIndex("UserIdUser");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SocketServer.Entities.Storage", b =>
                {
                    b.Property<int>("IdDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("StorageLimitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsedStorageBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserIdUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDevice");

                    b.HasIndex("UserIdUser");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("SocketServer.Entities.Transference", b =>
                {
                    b.Property<int>("idTranference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceDestinationIdDevice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceOriginIdDevice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileExtention")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserIdUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("idTranference");

                    b.HasIndex("DeviceDestinationIdDevice");

                    b.HasIndex("DeviceOriginIdDevice");

                    b.HasIndex("UserIdUser");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("SocketServer.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SocketServer.Entities.VerificationCode", b =>
                {
                    b.Property<int>("IdCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("IdCode");

                    b.ToTable("VerificationCodes");
                });

            modelBuilder.Entity("SocketServer.Entities.Device", b =>
                {
                    b.HasOne("SocketServer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocketServer.Entities.Storage", b =>
                {
                    b.HasOne("SocketServer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocketServer.Entities.Transference", b =>
                {
                    b.HasOne("SocketServer.Entities.Device", "DeviceDestination")
                        .WithMany()
                        .HasForeignKey("DeviceDestinationIdDevice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocketServer.Entities.Device", "DeviceOrigin")
                        .WithMany()
                        .HasForeignKey("DeviceOriginIdDevice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocketServer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceDestination");

                    b.Navigation("DeviceOrigin");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
